name       : popt
version    : '1.16'
release    : 6
source     :
    - http://rpm5.org/files/popt/popt-1.16.tar.gz : e728ed296fe9f069a0e005003c3d6b2dde3d9cad453422a10d6558616d304cc8
homepage   : http://directory.fsf.org/wiki/Popt
license    : MIT
summary    : popt
component  : system.base
description: |
    The popt package contains the popt libraries which are used by some programs to parse command-line options.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
