name       : popt
version    : '1.18'
release    : 7
source     :
    - https://github.com/rpm-software-management/popt/archive/refs/tags/popt-1.18-release.tar.gz : 36245242c59b5a33698388e415a3e1efa2d48fc4aead91aeb2810b4c0744f4e3
homepage   : https://github.com/rpm-software-management/popt
license    : MIT
summary    : popt
component  : system.base
description: |
    The popt package contains the popt libraries which are used by some programs to parse command-line options.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
